# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: Build
FROM node:20-alpine AS builder

# Install build dependencies
RUN apk add --no-cache build-base

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application source code
COPY src ./src
COPY tsconfig.json ./

# Build the application
RUN npm run build

# Stage 2: Run
FROM node:20-alpine AS runner

# Install wget
RUN apk add --no-cache wget

# Set the working directory
WORKDIR /app

# Copy the built application from the builder stage
COPY --from=builder /app/build ./build
COPY package.json ./

# Use a non-root user
RUN addgroup -g 1001 appgroup && adduser -D -G appgroup -u 1001 appuser
USER appuser

# Command to run the server
ENTRYPOINT ["node", "build/index.js"]
